### ISSUE TITLE
Connect to a mongodb database

### ISSUE THREAD

**Issue by hinchley2018** [hinchley2018/travelr-example#2]
**Goal**: have a mongodb wired up to the app so we can pull data from the database

## Todos
- [ ] fork this project and clone your forked copy locally
- [ ] Create a local mongodb db `travelr` if it you don't already have one
- [ ] Add a destinations collection if it doesn't exist yet (see destinations.json for data to import)
- [ ] Add mongoose package and configure it following [this example](https://github.com/hinchley2018/mongoose-explanation) or the [bakery-project](https://github.com/hinchley2018/bakery-activity)
- [ ] make sure mongouri is not hardcoded in your node.js script, pull it from .env
- [ ] grab destinations data from mongodb using mongoose instead of the hardcoded destinations array (do this in GET `/api/destinations`
- [ ] test that the index page still renders data
- [ ] make a PR! make sure to include #2 in your PR description so it links to this ticket
